# Generated by Django 4.2.16 on 2025-01-10 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='addProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='', max_length=50)),
                ('led_by', models.CharField(default='', max_length=100)),
                ('review', models.CharField(default='Monday', max_length=50)),
                ('research_deadline', models.DateField(auto_now_add=True)),
                ('research_effort', models.CharField(max_length=5)),
                ('design_deadline', models.DateField(auto_now_add=True)),
                ('design_effort', models.CharField(max_length=5)),
                ('development_deadline', models.DateField(auto_now_add=True)),
                ('development_effort', models.CharField(max_length=5)),
                ('testing_deadline', models.DateField(auto_now_add=True)),
                ('testing_effort', models.CharField(max_length=5)),
                ('assigned_by', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('current_milestone', models.CharField(default='Research', max_length=200)),
                ('last_update', models.DateField(default=django.utils.timezone.now)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='pm_api.addproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('team_manager', models.CharField(max_length=255)),
                ('team_location', models.CharField(max_length=255)),
                ('team_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(editable=False)),
                ('progress', models.TextField(default='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='pm_api.assignedproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LatestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_update', models.TextField()),
                ('posted_by', models.CharField(max_length=200)),
                ('posting_time', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_update', to='pm_api.addproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_description', models.TextField()),
                ('posting_time', models.DateField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=200)),
                ('is_added', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_feedback', to='pm_api.addproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dailyprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('progress', models.TextField(default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('posting_time', models.DateField(auto_now_add=True)),
                ('posted_by', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bugs', to='pm_api.addproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
