# Generated by Django 4.2.16 on 2025-01-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='project',
        ),
        migrations.RemoveField(
            model_name='weeklyprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='AssignedProject',
        ),
        migrations.DeleteModel(
            name='WeeklyProgress',
        ),
    ]
