# Generated by Django 4.2.16 on 2025-01-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0002_remove_weeklyprogress_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='pm_api.addproject'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
