# Generated by Django 4.2.16 on 2025-01-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0003_dailyprogress_project_dailyprogress_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprogress',
            old_name='user_name',
            new_name='name',
        ),
    ]
