# Generated by Django 4.2.16 on 2025-01-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0004_rename_user_name_dailyprogress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='project_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
