# Generated by Django 4.2.16 on 2025-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0005_addproject_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='assigned_to',
            field=models.CharField(default='', max_length=200),
        ),
    ]
