# Generated by Django 4.2.16 on 2025-01-21 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0006_feedback_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='current_milestone',
            field=models.CharField(default='Null', max_length=200),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='design_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='development_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='research_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='testing_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
