# Generated by Django 4.2.16 on 2025-01-22 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0008_alter_addproject_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
