# Generated by Django 4.2.16 on 2025-01-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0009_alter_addproject_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='project_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
