# Generated by Django 4.2.16 on 2025-01-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0010_alter_addproject_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_bug',
            field=models.BooleanField(default=False),
        ),
    ]
