# Generated by Django 4.2.16 on 2025-01-31 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0013_addproject_is_added_feedback_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='is_added_feedback_count',
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='total_feedback_count',
        ),
    ]
