# Generated by Django 4.2.16 on 2025-02-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0014_remove_addproject_is_added_feedback_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationindividual',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
