# Generated by Django 4.2.16 on 2025-02-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0015_registrationindividual_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reported_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
