# Generated by Django 5.1.4 on 2025-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0017_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='posting_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
