# Generated by Django 5.1.4 on 2025-02-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0018_alter_feedback_posting_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['project', 'project_index']},
        ),
        migrations.AddField(
            model_name='feedback',
            name='project_index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
