# Generated by Django 5.1.4 on 2025-02-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0020_alter_feedback_project_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
