# Generated by Django 5.1.4 on 2025-02-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0021_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
