# Generated by Django 5.1.4 on 2025-02-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0022_feedback_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
