# Generated by Django 5.1.4 on 2025-02-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0023_feedback_completion_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='is_added',
            new_name='is_feedback_closed',
        ),
    ]
