# Generated by Django 5.1.4 on 2025-02-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0025_rename_is_feedback_closed_feedback_is_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='is_added',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_feedback_closed',
            field=models.BooleanField(default=False),
        ),
    ]
