# Generated by Django 5.1.4 on 2025-03-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0027_rename_is_feedback_closed_feedback_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogress',
            name='isHoliday',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
