# Generated by Django 5.1.4 on 2025-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm_api', '0028_dailyprogress_isholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='onHold_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='onHold_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='assigned_to',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='project_name',
            field=models.CharField(max_length=500),
        ),
    ]
